### ISSUE TITLE
 error: Could not compile syntex_syntax

### ISSUE THREAD

**Issue by lionas89** [ComlOnline/librespot#8]
Good day, 

can you help me compile it? I get an error: Could not compile syntex_syntax.

**Comment by ComlOnline** [comment]
I had this exact error once.
I think [this ](https://github.com/racer-rust/racer/issues/388)is what helped.

From memory is was due to a versioning issue.

Let me know if you need more help.

Coml

**Comment by lionas89** [comment]
Thank you for the reply I will try to update rustup and check it if it helps.

**Comment by lionas89** [comment]
Hello,

I need help, I can't find how to downgrade rust. I'm using rustup.

**Comment by ComlOnline** [comment]
Hey @lionas89, 

Just wondering why you are downgrading rust?

I've just complied it on the latest to check and also made Travis do it again to confirm.

Can you share more of the errors you are getting. (If they are very ling use a gist or pastebin)

Coml

**Comment by lionas89** [comment]
Hello,

Thank you for the response. 

In the link you provided, one user message was: 

> But then I had to brew switch rust 1.1.0 backwards because bad cargo is in the homebrew rust 1.2.0 package: Homebrew/homebrew#42992 

Sure I can: 
   Compiling syntex_syntax v0.58.1
     Running `rustc --crate-name syntex_syntax /root/.cargo/registry/src/github.                                           com-1ecc6299db9ec823/syntex_syntax-0.58.1/src/lib.rs --crate-type lib --emit=dep                                           -info,link -C opt-level=3 -C metadata=1b8dae9622393ef1 -C extra-filename=-1b8dae                                           9622393ef1 --out-dir /root/librespot/target/release/deps -L dependency=/root/lib                                           respot/target/release/deps --extern log=/root/librespot/target/release/deps/libl                                           og-e39aafb8710f86e3.rlib --extern unicode_xid=/root/librespot/target/release/dep                                           s/libunicode_xid-b0d47ff4e5256777.rlib --extern rustc_serialize=/root/librespot/                                           target/release/deps/librustc_serialize-c2609f6283a547ab.rlib --extern syntex_pos                                           =/root/librespot/target/release/deps/libsyntex_pos-0f2ee0f823e73c39.rlib --exter                                           n syntex_errors=/root/librespot/target/release/deps/libsyntex_errors-3ba41ee7b60                                           654b8.rlib --extern bitflags=/root/librespot/target/release/deps/libbitflags-2f9                                           abeef2a0eea3e.rlib --cap-lints allow`
error: Could not compile `syntex_syntax`.

Caused by:
  process didn't exit successfully: `rustc --crate-name syntex_syntax /root/.car                                           go/registry/src/github.com-1ecc6299db9ec823/syntex_syntax-0.58.1/src/lib.rs --cr                                           ate-type lib --emit=dep-info,link -C opt-level=3 -C metadata=1b8dae9622393ef1 -C                                            extra-filename=-1b8dae9622393ef1 --out-dir /root/librespot/target/release/deps                                            -L dependency=/root/librespot/target/release/deps --extern log=/root/librespot/t                                           arget/release/deps/liblog-e39aafb8710f86e3.rlib --extern unicode_xid=/root/libre                                           spot/target/release/deps/libunicode_xid-b0d47ff4e5256777.rlib --extern rustc_ser                                           ialize=/root/librespot/target/release/deps/librustc_serialize-c2609f6283a547ab.r                                           lib --extern syntex_pos=/root/librespot/target/release/deps/libsyntex_pos-0f2ee0                                           f823e73c39.rlib --extern syntex_errors=/root/librespot/target/release/deps/libsy                                           ntex_errors-3ba41ee7b60654b8.rlib --extern bitflags=/root/librespot/target/relea                                           se/deps/libbitflags-2f9abeef2a0eea3e.rlib --cap-lints allow` (signal: 9, SIGKILL : kill)

**Comment by ComlOnline** [comment]
Ah I see what's happened, from what I've seen the latest release is fine.

What operating system are you using? 
Have you tried running "rustup update"?

**Comment by lionas89** [comment]
Here is information:

chip
    description: Computer
    product: NextThing C.H.I.P.
    serial: 1625420905014190
    width: 32 bits
  *-core
       description: Motherboard
       physical id: 0
       capabilities: nextthing_chip allwinner_sun5i-r8
     *-cpu
          description: CPU
          product: cpu
          physical id: 0
          bus info: cpu@0
          size: 1008MHz
          capacity: 1008MHz
          capabilities: cpufreq
     *-memory
          description: System memory
          physical id: 1
          size: 490MiB
  *-usbhost:0
       product: MUSB HDRC host driver
       vendor: Linux 4.4.13-ntc-mlc musb-hcd
       physical id: 2
       bus info: usb@3
       logical name: usb3
       version: 4.04
       capabilities: usb-2.00
       configuration: driver=hub slots=1 speed=480Mbit/s
  *-usbhost:1
       product: Generic Platform OHCI controller
       vendor: Linux 4.4.13-ntc-mlc ohci_hcd
       physical id: 3
       bus info: usb@2
       logical name: usb2
       version: 4.04
       capabilities: usb-1.10
       configuration: driver=hub slots=1 speed=12Mbit/s
  *-usbhost:2
       product: EHCI Host Controller
       vendor: Linux 4.4.13-ntc-mlc ehci_hcd
       physical id: 1
       bus info: usb@1
       logical name: usb1
       version: 4.04
       capabilities: usb-2.00
       configuration: driver=hub slots=1 speed=480Mbit/s
  *-network:0
       description: Wireless interface
       physical id: 4
       logical name: wlan0
       serial: 7c:c7:09:61:60:9a
       capabilities: ethernet physical wireless
       configuration: broadcast=yes driver=rtl8723bs ip=192.168.1.142 multicast=                                           yes wireless=IEEE 802.11bgn
  *-network:1
       description: Ethernet interface
       physical id: 5
       logical name: usb0
       serial: da:e8:a0:6d:b5:d2
       capabilities: ethernet physical
       configuration: broadcast=yes driver=g_ether driverversion=29-May-2008 fir                                           mware=musb-hdrc link=no multicast=yes
  *-network:2 DISABLED
       description: Wireless interface
       physical id: 6
       logical name: wlan1
       serial: 7e:c7:09:61:60:9a
       capabilities: ethernet physical wireless
       configuration: broadcast=yes driver=rtl8723bs multicast=yes wireless=unas                                           sociated


root@chip:~# rustup update
info: syncing channel updates for 'stable-armv7-unknown-linux-gnueabihf'
info: checking for self-updates

  stable-armv7-unknown-linux-gnueabihf unchanged - rustc 1.23.0 (766bd11c8 2018-01-01)

**Comment by ComlOnline** [comment]
And you got the same error after the update?
Have you tried from a fresh install?
And did you run:
`sudo apt-get update`
`sudo apt-get upgrade`
to get it all up to date?
I presume you are running CHIP Operating System?

(Note: I don'r have a CHIP to help you but am looking at buying one. Also I think the above commands are correct from the documentation.)

**Comment by lionas89** [comment]
Yes,
here is the output:
https://pastebin.com/pcdKPTt1

**Comment by ComlOnline** [comment]
Sorry for the long wait for a reply! 

I'm looking at your logs now

**Comment by lionas89** [comment]
Hello,

Thank you. I'm waiting for your response. :)

**Comment by ComlOnline** [comment]
Just to confirm you have tried a complete reinstall of CHIP OS and install of rust using rustup?

**Comment by lionas89** [comment]
Yes, I have tried fresh CHI and install using rustup. I followed @Brat steps. Tried his compiled version of @Brat, but I got an error: 
root@chip:~/Downloads# ./librespot --name "CHIP" --username "xxxxx" --password "xxxxx" RUST_BACKTRACE=1
INFO:librespot: librespot 67deb07 (2017-06-30). Built on 2017-07-05.
INFO:librespot::session: Connecting to AP "gew1-accesspoint-b-kzpq.ap.spotify.com:4070"
INFO:librespot::session: Authenticated as "xxxxxxx" !
INFO:librespot::session: Country: "LT"
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: WireError("invalid value for enum: 13")', /checkout/src/libcore/result.rs:859
note: Run with `RUST_BACKTRACE=1` for a backtrace.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', /checkout/src/libcore/result.rs:859

Thank you very much for help. 👍

**Comment by ComlOnline** [comment]
Try running it without the username and password so just   
```

```
./librespot --name "CHIP"
```

```

**Comment by lionas89** [comment]
Same issue. This appears when I try to connect with remote device to play song.

**Comment by ComlOnline** [comment]
OK I'm running a cross compiling job now and will upload the version that may work for you.

And as you saw I have commented asking if brad had any success with this fork.

**Comment by ComlOnline** [comment]
MD5: e732d71c2b8a36c22c3aae71a96aa059
SHA256:7b9b50d93c8e628bc7b55f36a6fbbb305229f7c77af98919c2ca132b71657946
[librespot.zip](https://github.com/ComlOnline/librespot/files/1654037/librespot.zip)

Try that it may work, though I won't get our hopes up.

**Comment by lionas89** [comment]
It is working at the moment. I can control it on my phone and it's what I need. Thank you very much. If I will face any issue I will let you know. Honestly, BIG THANK YOU!!! 🥇

**Comment by ComlOnline** [comment]
No problem :) That's good to hear! Not quite sure what caused your issue but Glad you have it sorted. 

I'll close this for now. Let me know if you have any other issues.

**Comment by crushert** [comment]
This seems to be exactly the problem I'm stuck with. Wanted to give the cross-compiled download a few posts up a try, but it doesn't seem to be available anymore. Not sure it would be the right platform anyway, though, I'm on a raspberry B+, not sure if that matches the CHIP.

While compiling the syntex_syntax, kswapd takes over all processing power at a certain moment, processor load goes up to 30+, and at some point the build process fails.

P.S. the reason I'm trying to compile my own librespot on the raspberry B+ is that the precompiled one I'm using now results in the following error shortly after starting it:

```thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: WireError("invalid value for enum: 13")', /checkout/src/libcore/result.rs:859```

P.P.S. I realise I'm replying to a closed issue, but since it seems to match the issue I'm having, I thought this would be better than opening a new issue. My apologies if that's not the desired way.

**Comment by crushert** [comment]
The precompiled librespot is clearly not matching my architecture, it segfaults upon startup. Raspotify, I had not heard of that, but that sounds very promising, I'll be sure to take a look at that! Thanks for pointing me there!

**Comment by ComlOnline** [comment]
Let me know if you have any more issues and I can cross compile one for the pi but Raspotify should sort you out.

**Comment by crushert** [comment]
Raspotify sorts me out, 98%. Now I'm stuck with an alsa issue, probably some other sound-related process preventing raspotify/librespot from accessing the device.

`Mar 04 12:58:09 max2play librespot[3045]: ERROR:librespot_playback::audio_backend::alsa: Alsa error PCM open -16`
`Mar 04 12:58:09 max2play librespot[3045]: ERROR:librespot_playback::player: Could not start audio: Alsa error: PCM open failed`

But now I'm diverting quite a bit from the original issue posted here, and I hope with some more searching on the internet and trying out I can figure this out... So, thanks for the help, issue closed for me.

Raspotify was an excellent suggestion, thanks for that!
